### PR TITLE
Update usage doc

### PR DESCRIPTION
**Pull request by jfchevrette**
I stumbled upon this cool project and found out that the usage output in the examples doc was outdated.

This PR updates the usage doc. Both master and the 0.2 release have the same usage doc.

### CODE REVIEW

**Comment by jzelinskie** [comment]
I think the examples need updating too, now that the default output isn't JSON, but the input format.

**Comment by jfchevrette** [comment]
@jzelinskie I've refactored the examples a little bit. Added an examples directory with sample files rather than relying on external sources that may change over time.

I've also removed the toml and torrent examples as they didn't work anymore and I couldn't figure out how to make them work.

```
# faq -r '.constraint[].name' Gopkg.toml

Error: failed to encode jq program output as auto: toml: top-level values must be Go maps or structs
```

```
# curl --silent -L https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.5.0-amd64-netinst.iso.torrent | faq -f bencode 'del(.info.pieces)'
                                                                                                                                     
Error: failed to encode jq program output as auto: Can't encode type: float64
```

WDYT?

**Comment by jzelinskie** [comment]
you have to output a different format -- like JSON for the TOML one because you can't have top level lists in a TOML file.

re-encoding large numbers is error prone, so we should probably output JSON for the bittorrent example too

**Comment by jzelinskie** [comment]
I fixed the examples after addressing the bug in bencode.
Also, we work together now, cool!

**Pull request closed without merging**
